version: '3.9'

services:
  wordpress:
    build:
      context: .
      dockerfile: wordpress.dockerfile
    container_name: worspress_container
    restart: always
    ports:
      - 8080:80
    volumes:
    - ./docker/wordpress/plugins/:/var/www/html/wp-content/plugins:rw
    - ./docker/wordpress/themes/:/var/www/html/wp-content/themes:rw
    - ./docker/wordpress/uploads/:/var/www/html/wp-content/uploads:rw
    depends_on:
      - mysqlbase
    environment:
     WORDPRESS_DB_HOST: mysqlbase
     WORDPRESS_DB_USER_FILE: /run/secrets/db_user
     WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_pass
     WORDPRESS_DB_NAME_FILE: /run/secrets/db_name
     SERVICE_TAGS: Testing
    secrets:
      - db_user
      - db_pass
      - db_name
    networks:
      draft_network:
        aliases:
          - wordpress_host
  
  app:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: php-fpm_app_container
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      draft_network:
        aliases:
          - php-fpm_app_host
  
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: always
    ports: 
      - 8000:80
    volumes: 
      - ./src/:/var/www:rw
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on: 
      - mysqlbase
    networks: 
      draft_network:
        aliases: 
          - nginx_host

  nginx_basic:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_basic_container
    restart: always
    ports:
      - 8181:80
    volumes:
      - ./docker/html:/usr/share/nginx/html:rw
    depends_on:
      - mysqlbase
    networks:
      draft_network:
        aliases:
          - nginx_basic_host

  
  mysqlbase:
    build:
      context: .
      dockerfile: mysql.dockerfile
    container_name: mysql_container
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./docker/mysql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
        MYSQL_DATABASE_FILE: /run/secrets/db_name
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
        MYSQL_PASSWORD_FILE: /run/secrets/db_pass
        MYSQL_USER_FILE: /run/secrets/db_user
        SERVICE_TAGS: Testing
    secrets:
          - db_name
          - db_root_pass
          - db_pass
          - db_user
    networks:
      draft_network:
        aliases:
          - mysql_host
  

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_root_pass:
    file: ./secrets/db_root_pass.txt
  db_pass:
    file: ./secrets/db_pass.txt
  db_user:
    file: ./secrets/db_user.txt
volumes:
  data: {}
  plugins: {}
  themes: {}
  html: {}
  uploads: {}
  src: {}
  nginx: {}
networks:
  draft_network:
    name: worspress_net
    driver: bridge
    ipam:
      driver: default


